name: "Build and Test"
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v12
      with:
        name: github-public
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: >
        git config --global url."https://github.com/".insteadOf ssh://git@github.com/
    - run: export NIXPKGS_ALLOW_UNFREE=1 && nix-build -E 'with (import (fetchTarball "https://github.com/goromal/anixpkgs/archive/refs/heads/master.tar.gz") {}); manif-geom-cpp.override { pkg-src = lib.cleanSource ./.; }'
  code-cov:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v12
      with:
        name: github-public
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Build, test, and generate coverage HTML report
      run: |
        mkdir build && cd build
        nix-shell ../.github/_nixshell --run "cmake .. -DCMAKE_BUILD_TYPE=Debug && make unit-tests"
        nix-shell ../.github/_nixshell --run "lcov --capture --directory . --output-file coverage.info && \
                                              lcov --remove coverage.info '/usr/*' '*/test/*' --output-file coverage.info.cleaned && \
                                              genhtml --ignore-errors source --output-directory coverage_report coverage.info.cleaned"
    - name: Setup LCOV
      uses: hrishikesh-kadam/setup-lcov@v1
    - name: Report code coverage
      uses: zgosalvez/github-actions-report-lcov@v4
      with:
        coverage-files: coverage.info.cleaned
        minimum-coverage: 90
        artifact-name: code-coverage-report
        github-token: ${{ secrets.GITHUB_TOKEN }}
        working-directory: build
        update-comment: true
